# Action name
name: Simple Test Action

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
  push

# Jobs section
jobs:
  simple-test:
    runs-on: ubuntu-latest
    container:
      image: southorange/ohos-base-zig:v4.1
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: cargo install ohrs && cargo install cargo-zigbuild

      - name: init project
        run: ohrs init hello

      - name: build aarch64-unknown-linux-ohos
        run: cd hello && cargo zigbuild --target aarch64-unknown-linux-ohos

      - name: build armv7-unknown-linux-ohos
        run: cd hello && cargo zigbuild --target armv7-unknown-linux-ohos
      
      - name: build x86_64-unknown-linux-ohos
        run: cd hello && cargo zigbuild --target x86_64-unknown-linux-ohos
